version: '2'
services:
  web:
    build: .
    ports:
        - "80:80"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "hireorbit"
      PGDATA: "/var/postgres/data/pgdata"
    volumes:
      - /var/postgres/data/pgdata:/var/postgres/data/pgdata
